### ISSUE TITLE
PuestoEnVagon

### ISSUE THREAD

**Issue by marco344444** [AngieMatson/FerroED2023#1]
en tiquete toca pedir el puesto en el que se va a sentar, dependiendo del vagon. Si el puesto esta ocupado tendra que escoger otro

**Comment by AngieMatson** [comment]
El puesto se asigna por el orden de compra.

**Comment by marco344444** [comment]
de hecho no, el profesor me habia dicho que el cliente podia esocger donde se sentaba, sin embargo si el puesto esta ocupado se podia cambiar donde queria sentarse

**Comment by AngieMatson** [comment]
Sí aclaró, es que hacer que el cliente elija es más difícil para programar

**Comment by marco344444** [comment]
lenin dijo que tocaba hacer eso, en parte estoy confundido por ello xd
